all:direct_mapped_cache.cpp direct_mapped_cache_lru.cpp
	g++ direct_mapped_cache.cpp -o direct_mapped_cache
    g++ direct_mapped_cache_lru.cpp -o direct_mapped_cache_lru
clean:
	rm  -f direct_mapped_cache direct_mapped_cache_lru 